### PR TITLE
Changes to build test container

### PR DESCRIPTION
**Pull request by smurugap**

### CODE REVIEW

**Comment by alexandrelevine** [comment]
What is this test container?
Is it usable for opensource community developers? 
Doesn't it refer to some of the closed source or obsolete stuff (I saw mentioning of fab)?
I suspect that placement of this test directory in this repo might be not totally suitable.

**Comment by smurugap** [comment]
Alex,

This is to build systest docker for zuulv3.
Where the containers/test/base will be snapshot once(need basis) and stored at dockerhub
and containers/test/newton(ocata) will be built for every CI job.

We are working on removing the dependency on fabric-utils from systest.
Once done we will be removing the same from the Dockerfile.

Thanks,
Senthil

**Comment by alexandrelevine** [comment]
Is it usable for opensource community developers?
Can it be invoked without the CI by someone who just downloaded and built containers locally? If it can't then it might be a wrong place to store. And definitely not correctly named.

**Comment by smurugap** [comment]
Yes, its usable by the community.
https://github.com/Juniper/contrail-test-ci/wiki/How-to-use-contrail-test-ci-container has info on how to use the systest container.

- Senthil

**Pull request merged**
